name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Tests
      run: |
        newman run api-tests/UserAPI.postman_collection.json \
          -e api-tests/QA.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export newman-report.html

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: newman-report.html
