name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  
permissions:
  contents: write
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Tests
      run: |
        newman run api-tests/UserAPI.postman_collection.json \
          -e api-tests/QA.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export newman-report.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
